# Generated by Django 3.2.9 on 2022-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_bot2',
            options={'verbose_name': 'Профили Воронки_1'},
        ),
    ]
