# Generated by Django 3.2.9 on 2022-05-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassageVor4_bot8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сообщения')),
                ('massege', models.TextField(verbose_name='Сообщение')),
                ('image', models.ImageField(blank=True, upload_to='avatars')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Voronka4',
            },
        ),
        migrations.DeleteModel(
            name='MassageVor4_bot7',
        ),
    ]
