# Generated by Django 3.2.9 on 2022-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_8', '0002_auto_20220517_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_bot8',
            options={'verbose_name': 'Профили_Воронки_1'},
        ),
        migrations.AlterModelOptions(
            name='profilevor2_bot8',
            options={'verbose_name': 'Профили_Воронки_2'},
        ),
        migrations.AlterModelOptions(
            name='profilevor3_bot8',
            options={'verbose_name': 'Профили_Воронки_3'},
        ),
        migrations.AlterModelOptions(
            name='profilevor4_bot8',
            options={'verbose_name': 'Профили_Воронки_4'},
        ),
        migrations.AlterModelOptions(
            name='profilevor5_bot8',
            options={'verbose_name': 'Профили_Воронки_5'},
        ),
    ]
