# Generated by Django 3.2.9 on 2022-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_bot4',
            options={'verbose_name': 'Профили_Воронки_1'},
        ),
        migrations.AlterModelOptions(
            name='profilevor2_bot4',
            options={'verbose_name': 'Профили_Воронки_2'},
        ),
        migrations.AlterModelOptions(
            name='profilevor3_bot4',
            options={'verbose_name': 'Профили_Воронки_3'},
        ),
        migrations.AlterModelOptions(
            name='profilevor4_bot4',
            options={'verbose_name': 'Профили_Воронки_4'},
        ),
        migrations.AlterModelOptions(
            name='profilevor5_bot4',
            options={'verbose_name': 'Профили_Воронки_5'},
        ),
    ]
