# Generated by Django 3.2.9 on 2022-05-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_4', '0003_auto_20220518_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage_bot4',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка:  '),
        ),
    ]
