"""
Django settings for Tgb project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cxe3wr%+=fbk))19q8$2$zw98*nlbzma0i2kp1eitf$la-kj0_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "admin_app",
    "Tgb",
    "Bot",
    "bot_2",
    "bot_3",
    "bot_4",
    "bot_5",
    "bot_6",
    "bot_7",
    "bot_8",
    "bot_9",
    "bot_10",




]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Tgb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tgb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TOKEN = "5307835139:AAEckIPDuuAqSzI2VlGtXjJRNZhLjVHBqcg"
TOKEN2 = "5376307361:AAH97YKbs9GoJ5rD6etIi7S9P4ZYvJkyJHQ"
TOKEN3 = "5398009269:AAF8pBpqveYlshtcWOK-Xcz2YbDnxQ-owlM"
TOKEN4 = "5338434531:AAEChDUjXtRotT7C984-zf79W-ZuxKR42og"
TOKEN5 = "5386175720:AAGVaAKVV8rqlcFSWxdTVZovP4qCn7x2XhU"
TOKEN6 = "5342259400:AAEozkvJjrEJ_PIZ6JKuo7JZGorBBxy7qn0"
TOKEN7 = "5370781904:AAFvDYv-y2xP23JDSIjyNv58HaBXfRWsad0"
TOKEN8 = "1676326401:AAHHPcUBIYIfTIHI0E3-DlXpJ4iz2TzfLsk"
TOKEN9 = "862039580:AAHUVPFTkRDgKqgMiMYB2zgX5kxNE71bScs"
TOKEN10 = "743360884:AAFD-XSqLP18_9YiITgNV3XLxc7RcjSIwVY"

