# Generated by Django 3.2.9 on 2022-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_6', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_bot6',
            options={'verbose_name': 'Профили_Вроронки_1'},
        ),
        migrations.AlterModelOptions(
            name='profilevor2_bot6',
            options={'verbose_name': 'Профили_Вроронки_2'},
        ),
        migrations.AlterModelOptions(
            name='profilevor3_bot6',
            options={'verbose_name': 'Профили_Вроронки_3'},
        ),
        migrations.AlterModelOptions(
            name='profilevor4_bot6',
            options={'verbose_name': 'Профили_Вроронки_4'},
        ),
        migrations.AlterModelOptions(
            name='profilevor5_bot6',
            options={'verbose_name': 'Профили_Вроронки_5'},
        ),
    ]
