# Generated by Django 3.2.9 on 2022-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
