# Generated by Django 3.2.9 on 2022-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_massage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название сообщения'),
        ),
    ]
