# Generated by Django 3.2.9 on 2022-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_massage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Название сообщения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя пользователя'),
        ),
    ]
