# Generated by Django 3.2.9 on 2022-05-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_auto_20220515_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': 'Voronka1'},
        ),
    ]
