# Generated by Django 3.2.9 on 2022-05-16 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_massage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
