# Generated by Django 3.2.9 on 2022-05-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_massagevor2_massagevor3_massagevor4_massagevor5_profilevor2_profilevor3_profilevor4_profilevor5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили_Воронки_1'},
        ),
        migrations.AlterModelOptions(
            name='profilevor2',
            options={'verbose_name': 'Профили_Воронки_2'},
        ),
        migrations.AlterModelOptions(
            name='profilevor3',
            options={'verbose_name': 'Профили_Воронки_3'},
        ),
        migrations.AlterModelOptions(
            name='profilevor4',
            options={'verbose_name': 'Профили_Воронки_4'},
        ),
        migrations.AlterModelOptions(
            name='profilevor5',
            options={'verbose_name': 'Профили_Воронки_5'},
        ),
        migrations.AddField(
            model_name='profilevor5',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='dadadadadadadw'),
            preserve_default=False,
        ),
    ]
