# Generated by Django 3.2.9 on 2022-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_auto_20220518_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilevor5',
            name='crib',
        ),
        migrations.AddField(
            model_name='massage',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='dadadadadadadw'),
            preserve_default=False,
        ),
    ]
