# Generated by Django 3.2.9 on 2022-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_auto_20220518_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagevor2',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
        migrations.AddField(
            model_name='massagevor3',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
        migrations.AddField(
            model_name='massagevor4',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
        migrations.AddField(
            model_name='massagevor5',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
        migrations.AlterField(
            model_name='massage',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
    ]
