# Generated by Django 3.2.9 on 2022-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_3', '0002_auto_20220518_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage_bot3',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
        migrations.AddField(
            model_name='massagevor2_bot3',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
        migrations.AddField(
            model_name='massagevor3_bot3',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
        migrations.AddField(
            model_name='massagevor4_bot3',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
        migrations.AddField(
            model_name='massagevor5_bot3',
            name='crib',
            field=models.CharField(default=1, max_length=200, verbose_name='Шпаргалка: '),
        ),
    ]
